---
- name: check param VAR_Zabbix_Agent_extracting_rolename subElement
  stat:
    path: "{{ VAR_Zabbix_Agent_gathering_dest }}/{{ inventory_hostname }}/Zabbix40_Agent_gathering_windows"
  delegate_to: localhost
  become: no
  register: file_exist

- name: parameter_generate run
  block:
  # 1-01  Zabbix_Agent Install Roleのパラメータ生成
    - name: Execute the parameter_generate module for Zabbix40-Agent_WIN_install
      parameter_generate:
        rolename: "{{ outer_item }}"
        collect_root: "{{ VAR_Zabbix_Agent_gathering_dest }}/{{ inventory_hostname }}/Zabbix40_Agent_gathering_windows"
        # config: "{{ mapping_definition }}"
        dest: "{{ VAR_Zabbix_Agent_extracting_dest }}"
        specific: "python {{ role_path }}/files/Zabbix40-Agent_WIN_install.py"
      when: outer_item == "Zabbix40-Agent_WIN_install"

  # 1-02　Zabbix_Agent設定Roleのパラメータ生成
    - name: Execute the parameter_generate module for Zabbix40-Agent_WIN_setup
      parameter_generate:
        rolename: "{{ outer_item }}"
        collect_root: "{{ VAR_Zabbix_Agent_gathering_dest }}/{{ inventory_hostname }}/Zabbix40_Agent_gathering_windows"
        # config: "{{ mapping_definition }}"
        dest: "{{ VAR_Zabbix_Agent_extracting_dest }}"
        specific: "python {{ role_path }}/files/Zabbix40-Agent_WIN_setup.py"

      when: outer_item == "Zabbix40-Agent_WIN_setup"

  # 1-03　Zabbix_Agent登録Roleのパラメータ生成
    - name: Execute the parameter_generate module for Zabbix40-Agent_WIN_regist
      parameter_generate:
        rolename: "{{ outer_item }}"
        collect_root: "{{ VAR_Zabbix_Agent_gathering_dest }}/{{ inventory_hostname }}/Zabbix40_Agent_gathering_windows"
        # config: "{{ mapping_definition }}"
        dest: "{{ VAR_Zabbix_Agent_extracting_dest }}"
        specific: "python {{ role_path }}/files/Zabbix40-Agent_WIN_regist.py"
      when: outer_item == "Zabbix40-Agent_WIN_regist"

  # 1-04　Zabbix_Agent OSセットロールパラメーターの生成
    - name: Execute the parameter_generate module for Zabbix40-Agent_WIN_ossetup
      parameter_generate:
        rolename: "{{ outer_item }}"
        collect_root: "{{ VAR_Zabbix_Agent_gathering_dest }}/{{ inventory_hostname }}/Zabbix40_Agent_gathering_windows"
        # config: "{{ mapping_definition }}"
        dest: "{{ VAR_Zabbix_Agent_extracting_dest }}"
        specific: "python {{ role_path }}/files/Zabbix40-Agent_WIN_ossetup.py"
      when: outer_item == "Zabbix40-Agent_WIN_ossetup"

  when: file_exist.stat.exists != false